// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nkfivkgnaxilwgfhxmyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rZml2a2duYXhpbHdnZmh4bXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTY1MTgsImV4cCI6MjA2MzQzMjUxOH0.y4noRz34SXGVsc6g_axclIakBBRrjVPoVqRli5U8lLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);